# Login - JWT - Cookies
POST http://localhost:8080/api/user/auth/login
Content-Type: application/json

{
  "email": "jonitafernandesrio@gmail.com",
  "password": "helloJonita?51"
}

> {% set-cookie %}

###

#Reset Password
POST http://localhost:8080/api/user/otp/reset-password?email=


###

#Verify Reset OTP
POST http://localhost:8080/api/user/otp/verify-reset-otp
Content-Type: application/json

{
  "email": "",
  "otp": ""
}


###

#Reset Password
POST http://localhost:8080/api/user/otp/new-password
Content-Type: application/json

{
  "email": "",
  "otp": "",
  "newPassword": ""
}