# Registration
POST http://localhost:8080/api/user/auth/register
Content-Type: application/json

{
  "name": "Jonita Fernandes",
  "email": "jonitafernandesrio@gmail.com",
  "password": "helloJonita?51"
}


###
# Otp verification
POST http://localhost:8080/api/user/otp/verify-account?email=jonitafernandesrio@gmail.com
Content-Type: application/json

{
  "otp": "815374"
}


###
# resend otp
POST http://localhost:8080/api/user/otp/resend-otp?email=