# Registration
POST http://localhost:8080/api/user/auth/register
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": ""
}


###
# Otp verification
POST http://localhost:8080/api/user/otp/verify-account?email=
Content-Type: application/json

{
  "otp": ""
}


###
# resend otp
POST http://localhost:8080/api/user/otp/resend-otp?email=